# Generated by Django 3.2.9 on 2021-11-29 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_auto_20211129_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone'), ('Electronic', 'Electronic'), ('Food', 'Food')], on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category'),
        ),
    ]
